from main import query
r = query("SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MAT' AND (COLUMN_NAME LIKE '%SLD%' OR COLUMN_NAME LIKE '%SALDO%' OR COLUMN_NAME LIKE '%MES%' OR COLUMN_NAME LIKE '%ANT%') ORDER BY ORDINAL_POSITION")
for x in r: print(x["COLUMN_NAME"])
